version: ~> 1.0
import: scala/scala-dev:travis/default.yml

language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  matrix:
    - ADOPTOPENJDK=11

  global:
    # encrypt with: travis encrypt --pro BINTRAY_USER=...
    - secure: "TV8cmq1UrtAmwxpaZTI89qEu+kYFgDqRJ2pm2F8TG75TmPWMUZ8YycYld8wWn2dMOXMc5mpDUYYXiJpqnxxiF90lYdCzN/TIJlLGEsHthXSS9UTHyqrCAh5JyT0XiQZmjP+6oCmWJLpdDayrgyTRqQNkUSFboEqN25aXJuCkCDw="
      # encrypt with: travis encrypt --pro BINTRAY_PASS=...
    - secure: "XHaF/fAX2H78Bc/5+nyQkSYLQfRX17SP4xBjF15iTxr9v9F2P0KxqsZ4qng2xHaQeUN122iXssOaZviQo4W+Z/o9FqoLXuUq9ukMol48RCFQjJXXnNNmdLmivetOJXOogAu9hHcRTeOoZ197RovIKbgnHIiavicsA3HMPNtm/bw="

jobs:
  include:
    - stage: test
      script: scripts/validate-code.sh
      name: "Code validations (headerCheck, scalafmt, mima)"

    - name: "Run tests with Scala 2.12 and AdoptOpenJDK 11"
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=2.12.13
        - ADOPTOPENJDK=11

    - name: "Run tests with Scala 2.13 and AdoptOpenJDK 11"
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=2.13.5
        - ADOPTOPENJDK=11

    - name: "Run tests with Scala 3 and AdoptOpenJDK 11"
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=3.0.0-RC1
        - ADOPTOPENJDK=11

    - name: "Run tests with Scala 2.12 and AdoptOpenJDK 8"
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=2.12.13
        - ADOPTOPENJDK=8

    - name: "Run tests with Scala 2.13 and AdoptOpenJDK 8"
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=2.13.5
        - ADOPTOPENJDK=8

    - name: "Run tests with Scala 3 and AdoptOpenJDK 8"
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=3.0.0-RC1
        - ADOPTOPENJDK=8

    - stage: docs
      script: scripts/validate-docs.sh
      name: "Validate documentation"

    - stage: publish
      name: "Publish artifacts to Bintray"
      script: sbt +publish

stages:
  - name: test
  - name: docs
  - name: publish
    # Snapshots from Bintray are picked up by a scheduled build on Lightbend's Vegemite
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
  slack:
    secure: lrBEBp00Fwr3T72GXK+eOaQVNy34QT+OBcJanr/WCVoD3kgt+L5hkEZ3iS9B7pDd26vMBcUGBb5kM8Z5QGo48gvbLUFgRtaTU00EBoTXbUPDIqlaMkuxdF+TN7GgS7yZKnKIInj54e7o1QaJ4R/I/Atw81kUJr0PNzMU0hfg6VU=

# safelist
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
